site_name: Bear Metal Docs
theme:
  name: material
  locale: en
  include_sidebar: true
  color_mode: dark
  user_color_mode_toggle: true
  nav_style: dark
nav: 
  - Home: 'index.md'
  - 'Design':
    - 'Design Home': '/design'
  - 'Electronics':
    - 'Electronics Home': '/electronics'
    - 'Motors': '/electronics/motors'
    - 'Components': '/electronics/components'


markdown_extensions:
  - admonition