site_name: Bear Metal Docs
theme:
  name: material
  locale: en
  logo: img/favicon.png
  favicon: img/favicon.png
  palette:
    scheme: slate
    primary: yellow
    accent: yellow
  font:
    text: Poppins
  features:
    - search.suggest
nav: 
  - Home: 'index.md'
  - 'Design':
    - 'Design HOME': '/design'
    - 'COTS Library': '/design/cots-library'
    - 'CAD Fundamentals': '/design/cad-fundamentals'
    - 'Iteration Process': '/design/iteration-process'
    - 'Int. Subteam Knowledge': '/design/inter-sub-knowledge'
    - 'Mech. Challenges': '/design/mech-challenges'
    - 'Org./Doc.': '/design/org-documentation'
    - 'Physics In Design': '/design/physics-in-design'
    - 'Strat. Design': '/design/strategic-design'
    - 'Sustainability': '/design/sustainability'
    - 'External Resources': '/design/external-resources'
  - 'Electronics':
    - 'Electronics Home': '/electronics'
    - 'Motors': '/electronics/motors'
    - 'Electrical Components': '/electronics/electrical-components'
    - 'Pneumatic Components': '/electronics/pneumatic-components'
plugins:
    - ffc-mkdocs-video
    - search
    - privacy
extra:
  generator: false
copyright: Site founded by Matt and Corbin 🦅

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
