site_name: Bear Metal Docs
theme:
  name: material
  locale: en
  logo: img/favicon.png
  favicon: img/favicon.png
  palette:
    scheme: slate
    primary: yellow
    accent: yellow
  font:
    text: Poppins
nav: 
  - Home: 'index.md'
  - 'Design':
    - 'Design Home': '/design'
    - 'Strategic Design': '/design/strategic-design'
  - 'Electronics':
    - 'Electronics Home': '/electronics'
    - 'Motors': '/electronics/motors'
    - 'Components': '/electronics/components'
plugins:
    - ffc-mkdocs-video
extra:
  generator: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences