site_name: Bear Metal Docs
theme:
  name: material
  locale: en
  logo: img/favicon.png
  favicon: img/favicon.png
  palette:
    scheme: slate
    primary: yellow
    accent: yellow
  font:
    text: Poppins
  features:
    - search.suggest
nav: 
  - Home: 'index.md'
  - 'Design':
    - 'Design Home': '/design'
    - 'Strategic Design': '/design/strategic-design'
  - 'Electronics':
    - 'Electronics Home': '/electronics'
    - 'Motors': '/electronics/motors'
    - 'Electrical Components': '/electronics/electrical-components'
    - 'Pneumatic Components': '/electronics/pneumatic-components'
plugins:
    - ffc-mkdocs-video
    - search
extra:
  generator: false
copyright: Site founded by Matt and Corbin 🦅

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets